package com.anlu.mapper;

import com.anlu.model.student;

public interface studentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Thu May 25 15:12:17 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Thu May 25 15:12:17 CST 2017
     */
    int insert(student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Thu May 25 15:12:17 CST 2017
     */
    int insertSelective(student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Thu May 25 15:12:17 CST 2017
     */
    student selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Thu May 25 15:12:17 CST 2017
     */
    int updateByPrimaryKeySelective(student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Thu May 25 15:12:17 CST 2017
     */
    int updateByPrimaryKey(student record);
}